#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-Architecture Map Generator
===============================
Scans the current project structure and generates ARCHITECTURE.txt automatically.
Ensures that the map always reflects the Reality (IST-State).
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Fallback path if env var is missing
# Dynamic Root
DEFAULT_ROOT = Path(os.getenv("EVOKI_PROJECT_ROOT", os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")))).resolve()
if not (DEFAULT_ROOT / "tooling").exists():
    DEFAULT_ROOT = Path(os.path.abspath(".")).resolve()
ROOT = Path(os.getenv("EVOKI_PROJECT_ROOT", DEFAULT_ROOT))
OUTPUT_FILE = ROOT / "ARCHITECTURE.txt"

# Dirs to ignore in the map
IGNORE_DIRS = {
    ".git", ".venv", ".venvs", "__pycache__", ".pytest_cache", 
    "node_modules", ".vscode", "coverage", "dist", "build", ".idea"
}

# Annotated Descriptions (Knowledge Base)
DESCRIPTIONS = {
    "app": "[PRODUCTION] State & Interface",
    "interface": "[FRONTEND] React + Vite",
    "deep_earth": "[MEMORY] SQLite Layers",
    "tooling": "[AUTOMATION] Logic & Dev Tools",
    "scripts": "[LOGIC] Automation Kernel",
    "automation": "Core Logic (Synapse Chain)",
    "daemons": "Background Watchers",
    "cli": "Admin Tools",
    "servers": "MCP Servers",
    "data": "[STATE] Runtime Data",
    "synapse": "Status Windows & Logs",
    "docs": "[KNOWLEDGE] Documentation",
    "tests": "[TESTS] Pytest Suite"
}

def generate_tree(directory: Path, prefix: str = "", is_last: bool = True):
    """Generates a tree string for a directory."""
    lines = []
    
    # Get filtered children (folders first, then files)
    try:
        children = sorted([p for p in directory.iterdir() if p.name not in IGNORE_DIRS], 
                         key=lambda x: (not x.is_dir(), x.name.lower()))
    except OSError:
        return []

    count = len(children)
    for i, path in enumerate(children):
        is_last_child = (i == count - 1)
        connector = "└─ " if is_last_child else "├─ "
        
        # Description lookup
        desc = f"  # {DESCRIPTIONS[path.name]}" if path.name in DESCRIPTIONS else ""
        if path.is_file() and path.name == "ARCHITECTURE.txt":
             desc = "  # THIS FILE"
        
        lines.append(f"{prefix}{connector}{path.name}{desc}")
        
        if path.is_dir():
            # Recursion
            extension = "   " if is_last_child else "│  "
            lines.extend(generate_tree(path, prefix + extension, is_last_child))
            
    return lines

def main():
    if not ROOT.exists():
        print(f"Error: Root path not found: {ROOT}")
        sys.exit(1)

    print(f"Generating Architecture Map for: {ROOT}")
    
    # Header
    content = [
        "EVOKI V3.0 - Architecture Map (Auto-Generated)",
        "==============================================",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "Strategy: Strict Separation (App vs Tooling)",
        "Status: LIVE REFLECTION",
        "",
        "ROOT/",
    ]
    
    # Tree
    content.extend(generate_tree(ROOT))
    
    # Footer
    content.append("")
    content.append("[NOTE]")
    content.append("This file is automatically generated by tooling/scripts/helpers/generate_architecture_map.py")
    content.append("Do not edit manually. Run the script instead.")

    # Write
    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("\n".join(content))
        print(f"✅ Map updated: {OUTPUT_FILE}")
    except Exception as e:
        print(f"❌ Failed to write map: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
