# tooling/scripts/automation/smoke_test_writer.ps1
# Generates a minimal Protocol V5 status window and writes it to pending_status.json

$ErrorActionPreference = "Stop"

# Resolve repo root dynamically (override with EVOKI_PROJECT_ROOT).
$PROJECT_ROOT = $env:EVOKI_PROJECT_ROOT
if ([string]::IsNullOrWhiteSpace($PROJECT_ROOT)) {
    # Fallback: repo root is 3 levels up from this file: tooling/scripts/automation -> repo root
    $here = Split-Path -Parent $MyInvocation.MyCommand.Path
    $PROJECT_ROOT = (Resolve-Path (Join-Path $here "..\..\..")).Path
}

$PENDING_PATH = Join-Path $PROJECT_ROOT "tooling\data\synapse\status\pending_status.json"

# Minimal V5 window that should pass strict validators (backend fills timestamp/hash/prev hash).
$status = @{
    schema_version   = "5.0"
    window_type      = "status_update"
    goal             = "Smoke test: V5 pipeline end-to-end"
    critical_summary = "Smoke test window generated by smoke_test_writer.ps1 (expected to be accepted & persisted)."

    # Backend authoritative time: writer requests AUTO (backend stamps ISO + STRICT_SYNC).
    time_source      = "...: AUTO"
    prev_window_hash = "AUTO"
    window_hash      = "PLACEHOLDER_BACKEND"

    confidence       = 0.85

    inputs           = @{
        raw_user_request = "Run smoke test: generate a V5 status window and push it through the pending watcher."
        user_messages    = @(
            "Smoke test triggered from PowerShell."
        )
        system_events    = @(
            "smoke_test_writer.ps1 invoked"
        )
        context          = @{
            trigger   = "smoke_test_writer.ps1"
            repo_root = $PROJECT_ROOT
        }
    }

    actions          = @(
        "Generate a minimal V5 status window"
        "Write to pending_status.json"
    )

    rule_tangency    = @{
        tangency_detected = $false
        notes             = "Smoke test: no rule-tangency analysis required."
    }

    reflection_curve = @{
        delta      = "Smoke test executed."
        correction = "If rejected, check V5 required fields + time_source format."
        next       = "Verify watcher appended entry to status_window_history.json."
    }

    output_plan      = @(
        "Verify watcher processes the window"
        "Confirm status_window_history.json contains the new entry"
    )

    risk             = @()
}

# Ensure target directory exists
$dir = Split-Path -Parent $PENDING_PATH
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

# Write JSON (UTF-8, no BOM)
$json = $status | ConvertTo-Json -Depth 12
[System.IO.File]::WriteAllText($PENDING_PATH, $json, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "OK: wrote pending status to: $PENDING_PATH"
